export const MAX_STORE_SESSIONS: number;
export function sessionId(signature: string): string;
export function findReusableSession<T extends { signature: string }>(sessions: T[], signature: string): T | null;
export function closeSession<T extends { id: string }>(sessions: T[], activeSessionId: string | null, closingId: string): { sessions: T[]; activeSessionId: string | null };
export function restoreSessions<T>(state: unknown): T[];
export type SnapshotDiffRow = { id: string; category: string; key: string; leftValue: number | null; rightValue: number | null; delta: number | null; status: "not-observed-left" | "not-observed-right" | "changed" };
export function collectSnapshotFacts(result: unknown): Map<string, number>;
export function buildSnapshotDiff(left: unknown, right: unknown): SnapshotDiffRow[];
export const LEAD_THRESHOLDS: Readonly<{ advisoryObservations: number; unknownRecords: number; journalConcentrationPercent: number; journalConcentrationMinimum: number }>;
export function createIncidentCase(now?: string, id?: string): import("./types").IncidentCase;
export function addCasePin(incident: import("./types").IncidentCase, pin: Omit<import("./types").CasePin, "pinnedAt">, now?: string): import("./types").IncidentCase;
export function addCaseNote(incident: import("./types").IncidentCase, text: string, now?: string, id?: string): import("./types").IncidentCase;
export function buildInvestigativeLeads(result: unknown, thresholds?: typeof LEAD_THRESHOLDS): Array<{ code: string; observed: number; threshold: number; detail?: string }>;
export type JournalRetentionRow = { id: string; path: string; fileId: number | null; size: number; modified: number; recordCount: number; referenceCount: number; firstOffset: number | null; lastOffset: number | null; destinations: string[]; commands: string[]; references: import("./types").EvidenceRef[]; sequence: "older-file-id" | "highest-file-id" | "unknown-order"; observation: "references-observed" | "records-observed" | "no-structured-observation" };
export function buildJournalRetentionIndex(result: unknown): JournalRetentionRow[];
export const MAX_TIMELINE_EVENTS: number;
export type TimelineEvent = { id: string; file: string; dataFileId: number | null; offset: number | null; command: string; category: "subscription" | "transaction" | "message" | "record"; destination: string; primaryId: string; status: string; confidence: import("./types").Confidence };
export function buildEvidenceTimeline(result: unknown, limit?: number): { events: TimelineEvent[]; total: number; truncated: boolean; ordering: "data-file-id-offset" };
